version: "3"
services:
  modelgate:
    image: ghcr.io/modelgate/modelgate:latest
    container_name: modelgate
    restart: always
    ports:
      - 8088:8088
      - 8080:8080
    environment:
      TZ: Asia/Shanghai
      MG_DATABASE_TYPE: ${MG_DATABASE_TYPE}
      MG_DATABASE_HOST: ${MG_DATABASE_HOST}
      MG_DATABASE_PORT: ${MG_DATABASE_PORT}
      MG_DATABASE_USER: ${MG_DATABASE_USER}
      MG_DATABASE_PASSWORD: ${MG_DATABASE_PASSWORD}
      MG_DATABASE_NAME: ${MG_DATABASE_NAME}
      MG_SECRET_KEY: ${MG_SECRET_KEY}
      MG_REDIS_HOST: ${MG_REDIS_HOST}
      MG_REDIS_PASSWORD: ${MG_REDIS_PASSWORD}
